from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 450)
        MainWindow.setMinimumSize(QtCore.QSize(600, 450))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sideaBar = QtWidgets.QFrame(self.centralwidget)
        self.sideaBar.setMinimumSize(QtCore.QSize(200, 0))
        self.sideaBar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sideaBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideaBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideaBar.setObjectName("sideaBar")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.sideaBar)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.titulo_11 = QtWidgets.QLabel(self.sideaBar)
        self.titulo_11.setMinimumSize(QtCore.QSize(160, 0))
        self.titulo_11.setMaximumSize(QtCore.QSize(160, 30))
        self.titulo_11.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_11.setObjectName("titulo_11")
        self.verticalLayout_13.addWidget(self.titulo_11)
        self.stackedWidget_4 = QtWidgets.QStackedWidget(self.sideaBar)
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.agregarServicio_4 = QtWidgets.QWidget()
        self.agregarServicio_4.setObjectName("agregarServicio_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.agregarServicio_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.codigo_8 = QtWidgets.QLineEdit(self.agregarServicio_4)
        self.codigo_8.setMaximumSize(QtCore.QSize(200, 30))
        self.codigo_8.setInputMask("")
        self.codigo_8.setText("")
        self.codigo_8.setMaxLength(32767)
        self.codigo_8.setObjectName("codigo_8")
        self.verticalLayout_14.addWidget(self.codigo_8)
        self.nombreServicio_4 = QtWidgets.QLineEdit(self.agregarServicio_4)
        self.nombreServicio_4.setMaximumSize(QtCore.QSize(200, 30))
        self.nombreServicio_4.setObjectName("nombreServicio_4")
        self.verticalLayout_14.addWidget(self.nombreServicio_4)
        self.origen_4 = QtWidgets.QLineEdit(self.agregarServicio_4)
        self.origen_4.setMaximumSize(QtCore.QSize(200, 30))
        self.origen_4.setObjectName("origen_4")
        self.verticalLayout_14.addWidget(self.origen_4)
        self.destino_4 = QtWidgets.QLineEdit(self.agregarServicio_4)
        self.destino_4.setMaximumSize(QtCore.QSize(200, 30))
        self.destino_4.setObjectName("destino_4")
        self.verticalLayout_14.addWidget(self.destino_4)
        self.precio_4 = QtWidgets.QLineEdit(self.agregarServicio_4)
        self.precio_4.setMaximumSize(QtCore.QSize(200, 30))
        self.precio_4.setObjectName("precio_4")
        self.verticalLayout_14.addWidget(self.precio_4)
        self.fecha_4 = QtWidgets.QDateEdit(self.agregarServicio_4)
        self.fecha_4.setMaximumSize(QtCore.QSize(200, 30))
        self.fecha_4.setObjectName("fecha_4")
        self.verticalLayout_14.addWidget(self.fecha_4)
        self.puestos_4 = QtWidgets.QLineEdit(self.agregarServicio_4)
        self.puestos_4.setMaximumSize(QtCore.QSize(200, 30))
        self.puestos_4.setObjectName("puestos_4")
        self.verticalLayout_14.addWidget(self.puestos_4)
        self.kilos_4 = QtWidgets.QLineEdit(self.agregarServicio_4)
        self.kilos_4.setMaximumSize(QtCore.QSize(200, 30))
        self.kilos_4.setObjectName("kilos_4")
        self.verticalLayout_14.addWidget(self.kilos_4)
        self.stackedWidget_4.addWidget(self.agregarServicio_4)
        self.agregarCliente_4 = QtWidgets.QWidget()
        self.agregarCliente_4.setObjectName("agregarCliente_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.agregarCliente_4)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.identificacion_4 = QtWidgets.QLineEdit(self.agregarCliente_4)
        self.identificacion_4.setMaximumSize(QtCore.QSize(200, 30))
        self.identificacion_4.setObjectName("identificacion_4")
        self.verticalLayout_15.addWidget(self.identificacion_4)
        self.nombreCliente_4 = QtWidgets.QLineEdit(self.agregarCliente_4)
        self.nombreCliente_4.setMaximumSize(QtCore.QSize(200, 30))
        self.nombreCliente_4.setObjectName("nombreCliente_4")
        self.verticalLayout_15.addWidget(self.nombreCliente_4)
        self.apellidoCliente_4 = QtWidgets.QLineEdit(self.agregarCliente_4)
        self.apellidoCliente_4.setMaximumSize(QtCore.QSize(200, 30))
        self.apellidoCliente_4.setObjectName("apellidoCliente_4")
        self.verticalLayout_15.addWidget(self.apellidoCliente_4)
        self.telefono_4 = QtWidgets.QLineEdit(self.agregarCliente_4)
        self.telefono_4.setMaximumSize(QtCore.QSize(200, 30))
        self.telefono_4.setObjectName("telefono_4")
        self.verticalLayout_15.addWidget(self.telefono_4)
        self.direccion_4 = QtWidgets.QLineEdit(self.agregarCliente_4)
        self.direccion_4.setMaximumSize(QtCore.QSize(200, 30))
        self.direccion_4.setText("")
        self.direccion_4.setObjectName("direccion_4")
        self.verticalLayout_15.addWidget(self.direccion_4)
        self.correoCliente_4 = QtWidgets.QLineEdit(self.agregarCliente_4)
        self.correoCliente_4.setMaximumSize(QtCore.QSize(200, 30))
        self.correoCliente_4.setText("")
        self.correoCliente_4.setObjectName("correoCliente_4")
        self.verticalLayout_15.addWidget(self.correoCliente_4)
        self.stackedWidget_4.addWidget(self.agregarCliente_4)
        self.agregarVenta_4 = QtWidgets.QWidget()
        self.agregarVenta_4.setObjectName("agregarVenta_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.agregarVenta_4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.noIdentificacionVenta_4 = QtWidgets.QLineEdit(self.agregarVenta_4)
        self.noIdentificacionVenta_4.setMaximumSize(QtCore.QSize(200, 30))
        self.noIdentificacionVenta_4.setObjectName("noIdentificacionVenta_4")
        self.verticalLayout_16.addWidget(self.noIdentificacionVenta_4)
        self.codigoVenta_4 = QtWidgets.QLineEdit(self.agregarVenta_4)
        self.codigoVenta_4.setMaximumSize(QtCore.QSize(200, 30))
        self.codigoVenta_4.setObjectName("codigoVenta_4")
        self.verticalLayout_16.addWidget(self.codigoVenta_4)
        self.cantidadVenta_4 = QtWidgets.QLineEdit(self.agregarVenta_4)
        self.cantidadVenta_4.setMaximumSize(QtCore.QSize(200, 30))
        self.cantidadVenta_4.setText("")
        self.cantidadVenta_4.setObjectName("cantidadVenta_4")
        self.verticalLayout_16.addWidget(self.cantidadVenta_4)
        self.titulo_12 = QtWidgets.QLabel(self.agregarVenta_4)
        self.titulo_12.setMinimumSize(QtCore.QSize(160, 0))
        self.titulo_12.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(6)
        font.setItalic(True)
        self.titulo_12.setFont(font)
        self.titulo_12.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_12.setObjectName("titulo_12")
        self.verticalLayout_16.addWidget(self.titulo_12)
        self.stackedWidget_4.addWidget(self.agregarVenta_4)
        self.verticalLayout_13.addWidget(self.stackedWidget_4)
        self.guardarCambio_4 = QtWidgets.QDialogButtonBox(self.sideaBar)
        self.guardarCambio_4.setMaximumSize(QtCore.QSize(200, 30))
        self.guardarCambio_4.setOrientation(QtCore.Qt.Horizontal)
        self.guardarCambio_4.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Save)
        self.guardarCambio_4.setCenterButtons(True)
        self.guardarCambio_4.setObjectName("guardarCambio_4")
        self.verticalLayout_13.addWidget(self.guardarCambio_4)
        self.gridLayout.addWidget(self.sideaBar, 0, 0, 1, 1)
        self.main = QtWidgets.QTabWidget(self.centralwidget)
        self.main.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setStyleSheet("")
        self.main.setTabPosition(QtWidgets.QTabWidget.North)
        self.main.setUsesScrollButtons(False)
        self.main.setDocumentMode(False)
        self.main.setTabsClosable(False)
        self.main.setMovable(False)
        self.main.setObjectName("main")
        self.servicios_4 = QtWidgets.QWidget()
        self.servicios_4.setObjectName("servicios_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.servicios_4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tablaServicios_4 = QtWidgets.QTableWidget(self.servicios_4)
        self.tablaServicios_4.setObjectName("tablaServicios_4")
        self.tablaServicios_4.setColumnCount(8)
        self.tablaServicios_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaServicios_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaServicios_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaServicios_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaServicios_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaServicios_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaServicios_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaServicios_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaServicios_4.setHorizontalHeaderItem(7, item)
        self.horizontalLayout_13.addWidget(self.tablaServicios_4)
        self.main.addTab(self.servicios_4, "")
        self.clientes_4 = QtWidgets.QWidget()
        self.clientes_4.setObjectName("clientes_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.clientes_4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tablaClientes_4 = QtWidgets.QTableWidget(self.clientes_4)
        self.tablaClientes_4.setObjectName("tablaClientes_4")
        self.tablaClientes_4.setColumnCount(6)
        self.tablaClientes_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaClientes_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaClientes_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaClientes_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaClientes_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaClientes_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaClientes_4.setHorizontalHeaderItem(5, item)
        self.horizontalLayout_14.addWidget(self.tablaClientes_4)
        self.main.addTab(self.clientes_4, "")
        self.ventas_4 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ventas_4.sizePolicy().hasHeightForWidth())
        self.ventas_4.setSizePolicy(sizePolicy)
        self.ventas_4.setObjectName("ventas_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.ventas_4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.tablaVentas_4 = QtWidgets.QTableWidget(self.ventas_4)
        self.tablaVentas_4.setObjectName("tablaVentas_4")
        self.tablaVentas_4.setColumnCount(4)
        self.tablaVentas_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.tablaVentas_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaVentas_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaVentas_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaVentas_4.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_15.addWidget(self.tablaVentas_4)
        self.main.addTab(self.ventas_4, "")
        self.gridLayout.addWidget(self.main, 0, 1, 1, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.verticalLayout_18.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_18.addWidget(self.label_2)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_19.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_19.addWidget(self.pushButton_11)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_19.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_19.addWidget(self.pushButton_8)
        self.verticalLayout_18.addLayout(self.verticalLayout_19)
        self.gridLayout.addLayout(self.verticalLayout_18, 0, 2, 1, 1)
        self.footer_4 = QtWidgets.QHBoxLayout()
        self.footer_4.setObjectName("footer_4")
        self.titulo_10 = QtWidgets.QLabel(self.centralwidget)
        self.titulo_10.setMinimumSize(QtCore.QSize(100, 0))
        self.titulo_10.setMaximumSize(QtCore.QSize(100, 30))
        self.titulo_10.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_10.setObjectName("titulo_10")
        self.footer_4.addWidget(self.titulo_10)
        self.codigo_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.codigo_7.setMaximumSize(QtCore.QSize(200, 30))
        self.codigo_7.setInputMask("")
        self.codigo_7.setText("")
        self.codigo_7.setMaxLength(32767)
        self.codigo_7.setObjectName("codigo_7")
        self.footer_4.addWidget(self.codigo_7)
        self.guardar_4 = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.guardar_4.setMaximumSize(QtCore.QSize(200, 30))
        self.guardar_4.setOrientation(QtCore.Qt.Horizontal)
        self.guardar_4.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Save)
        self.guardar_4.setCenterButtons(True)
        self.guardar_4.setObjectName("guardar_4")
        self.footer_4.addWidget(self.guardar_4)
        self.gridLayout.addLayout(self.footer_4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 881, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuEditar = QtWidgets.QMenu(self.menuBar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuArchivo = QtWidgets.QMenu(self.menuBar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAyuda = QtWidgets.QMenu(self.menuBar)
        self.menuAyuda.setObjectName("menuAyuda")
        self.menuVista = QtWidgets.QMenu(self.menuBar)
        self.menuVista.setObjectName("menuVista")
        self.menuVentana = QtWidgets.QMenu(self.menuBar)
        self.menuVentana.setObjectName("menuVentana")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionDocumentaci_n = QtWidgets.QAction(MainWindow)
        self.actionDocumentaci_n.setObjectName("actionDocumentaci_n")
        self.actionDeshacer = QtWidgets.QAction(MainWindow)
        self.actionDeshacer.setObjectName("actionDeshacer")
        self.actionRehacer = QtWidgets.QAction(MainWindow)
        self.actionRehacer.setObjectName("actionRehacer")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionSali = QtWidgets.QAction(MainWindow)
        self.actionSali.setObjectName("actionSali")
        self.actionfhdsjafd = QtWidgets.QAction(MainWindow)
        self.actionfhdsjafd.setObjectName("actionfhdsjafd")
        self.actionCortar = QtWidgets.QAction(MainWindow)
        self.actionCortar.setObjectName("actionCortar")
        self.actionCopiar = QtWidgets.QAction(MainWindow)
        self.actionCopiar.setObjectName("actionCopiar")
        self.actionPegar = QtWidgets.QAction(MainWindow)
        self.actionPegar.setObjectName("actionPegar")
        self.actionEliminar = QtWidgets.QAction(MainWindow)
        self.actionEliminar.setObjectName("actionEliminar")
        self.actionModo_oscuro = QtWidgets.QAction(MainWindow)
        self.actionModo_oscuro.setObjectName("actionModo_oscuro")
        self.actionMinimizar = QtWidgets.QAction(MainWindow)
        self.actionMinimizar.setObjectName("actionMinimizar")
        self.actionMaximizar = QtWidgets.QAction(MainWindow)
        self.actionMaximizar.setObjectName("actionMaximizar")
        self.actionAcerca_de_SAT = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de_SAT.setObjectName("actionAcerca_de_SAT")
        self.actionDocumentaci_n_de_usuario = QtWidgets.QAction(MainWindow)
        self.actionDocumentaci_n_de_usuario.setObjectName("actionDocumentaci_n_de_usuario")
        self.menuEditar.addAction(self.actionDeshacer)
        self.menuEditar.addAction(self.actionRehacer)
        self.menuEditar.addSeparator()
        self.menuEditar.addAction(self.actionCortar)
        self.menuEditar.addAction(self.actionCopiar)
        self.menuEditar.addAction(self.actionPegar)
        self.menuEditar.addAction(self.actionEliminar)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSali)
        self.menuAyuda.addAction(self.actionAcerca_de_SAT)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionDocumentaci_n)
        self.menuAyuda.addAction(self.actionDocumentaci_n_de_usuario)
        self.menuVista.addAction(self.actionModo_oscuro)
        self.menuVentana.addAction(self.actionMinimizar)
        self.menuVentana.addAction(self.actionMaximizar)
        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuEditar.menuAction())
        self.menuBar.addAction(self.menuVista.menuAction())
        self.menuBar.addAction(self.menuVentana.menuAction())
        self.menuBar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget_4.setCurrentIndex(0)
        self.main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SAT La nacional"))
        self.titulo_11.setText(_translate("MainWindow", "Agregar un dato"))
        self.codigo_8.setPlaceholderText(_translate("MainWindow", "Código"))
        self.nombreServicio_4.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.origen_4.setPlaceholderText(_translate("MainWindow", "Origen"))
        self.destino_4.setPlaceholderText(_translate("MainWindow", "Destino"))
        self.precio_4.setPlaceholderText(_translate("MainWindow", "Precio"))
        self.puestos_4.setPlaceholderText(_translate("MainWindow", "Puestos"))
        self.kilos_4.setPlaceholderText(_translate("MainWindow", "Kilos"))
        self.identificacion_4.setPlaceholderText(_translate("MainWindow", "Identificación"))
        self.nombreCliente_4.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.apellidoCliente_4.setPlaceholderText(_translate("MainWindow", "Apellido"))
        self.telefono_4.setPlaceholderText(_translate("MainWindow", "Teléfono"))
        self.direccion_4.setPlaceholderText(_translate("MainWindow", "Dirección"))
        self.correoCliente_4.setPlaceholderText(_translate("MainWindow", "Correo"))
        self.noIdentificacionVenta_4.setPlaceholderText(_translate("MainWindow", "Identificación"))
        self.codigoVenta_4.setPlaceholderText(_translate("MainWindow", "Código"))
        self.cantidadVenta_4.setPlaceholderText(_translate("MainWindow", "Cantidad"))
        self.titulo_12.setText(_translate("MainWindow", "*El No. de factura se genera automáticamente"))
        item = self.tablaServicios_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Código"))
        item = self.tablaServicios_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tablaServicios_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Origen"))
        item = self.tablaServicios_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Destino"))
        item = self.tablaServicios_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Precio"))
        item = self.tablaServicios_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tablaServicios_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Puestos"))
        item = self.tablaServicios_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Kilos "))
        self.main.setTabText(self.main.indexOf(self.servicios_4), _translate("MainWindow", "Servicios"))
        item = self.tablaClientes_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Identificación"))
        item = self.tablaClientes_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tablaClientes_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellido"))
        item = self.tablaClientes_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Teléfono"))
        item = self.tablaClientes_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Dirección"))
        item = self.tablaClientes_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Correo"))
        self.main.setTabText(self.main.indexOf(self.clientes_4), _translate("MainWindow", "Clientes"))
        item = self.tablaVentas_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No Factura"))
        item = self.tablaVentas_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Identificación"))
        item = self.tablaVentas_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Código"))
        item = self.tablaVentas_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cantidad"))
        self.main.setTabText(self.main.indexOf(self.ventas_4), _translate("MainWindow", "Ventas"))
        self.label.setText(_translate("MainWindow", "Factura"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_10.setText(_translate("MainWindow", "Enviar correo de factura"))
        self.pushButton_11.setText(_translate("MainWindow", "Imprimir factura"))
        self.pushButton_9.setText(_translate("MainWindow", "agregar servicio a factura"))
        self.pushButton_8.setText(_translate("MainWindow", "Eliminar servicio de factura"))
        self.titulo_10.setText(_translate("MainWindow", "Editar Selecionado"))
        self.codigo_7.setPlaceholderText(_translate("MainWindow", "Nuevo nombre"))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.menuVista.setTitle(_translate("MainWindow", "Vista"))
        self.menuVentana.setTitle(_translate("MainWindow", "Ventana"))
        self.actionDocumentaci_n.setText(_translate("MainWindow", "Documentación técnica"))
        self.actionDeshacer.setText(_translate("MainWindow", "Deshacer"))
        self.actionRehacer.setText(_translate("MainWindow", "Rehacer"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionSali.setText(_translate("MainWindow", "Salir del programa"))
        self.actionfhdsjafd.setText(_translate("MainWindow", "fhdsjafd"))
        self.actionCortar.setText(_translate("MainWindow", "Cortar"))
        self.actionCopiar.setText(_translate("MainWindow", "Copiar"))
        self.actionPegar.setText(_translate("MainWindow", "Pegar"))
        self.actionEliminar.setText(_translate("MainWindow", "Eliminar"))
        self.actionModo_oscuro.setText(_translate("MainWindow", "Modo oscuro"))
        self.actionMinimizar.setText(_translate("MainWindow", "Minimizar"))
        self.actionMaximizar.setText(_translate("MainWindow", "Maximizar"))
        self.actionAcerca_de_SAT.setText(_translate("MainWindow", "Acerca de SAT"))
        self.actionDocumentaci_n_de_usuario.setText(_translate("MainWindow", "Documentación usuario"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
